-- Goal Guide BD: Contact Us page settings and private Admin message inbox.
-- Run this in the Supabase SQL Editor for the project's existing public anon key.
-- Create trusted inbox users in Supabase Dashboard > Authentication > Users.

create table if not exists public.contact_page_settings (
  id integer primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint contact_page_settings_singleton_id check (id = 1)
);

alter table public.contact_page_settings enable row level security;
grant select, insert, update on public.contact_page_settings to anon, authenticated;

drop policy if exists "Public can read contact page settings" on public.contact_page_settings;
create policy "Public can read contact page settings"
  on public.contact_page_settings for select to anon, authenticated
  using (id = 1);

drop policy if exists "Admin client can insert contact page settings" on public.contact_page_settings;
create policy "Admin client can insert contact page settings"
  on public.contact_page_settings for insert to anon, authenticated
  with check (id = 1);

drop policy if exists "Admin client can update contact page settings" on public.contact_page_settings;
create policy "Admin client can update contact page settings"
  on public.contact_page_settings for update to anon, authenticated
  using (id = 1)
  with check (id = 1);

insert into public.contact_page_settings (id, content)
values (
  1,
  '{
    "map_url": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d116806.74519572966!2d90.21653799726562!3d23.811102400000006!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c11b7398e455%3A0x4bdf5a372762e77b!2sGoal%20Guide!5e0!3m2!1sbn!2sbd!4v1790457868427!5m2!1sbn!2sbd",
    "whatsapp": "+88 01717099770",
    "phone": "+88 01717099770",
    "email": "info.waisbd@gmail.com",
    "address": "House 2/1, 3rd Floor, Kalabagan, Dhanmondi, Dhaka 1205",
    "facebook": "https://facebook.com/",
    "youtube": "https://youtube.com/"
  }'::jsonb
)
on conflict (id) do nothing;

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 254),
  phone text not null check (char_length(phone) between 1 and 40),
  message text not null check (char_length(message) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index if not exists contact_messages_created_at_idx
  on public.contact_messages (created_at desc);

alter table public.contact_messages enable row level security;
grant insert on public.contact_messages to anon, authenticated;
grant select, delete on public.contact_messages to authenticated;
grant usage, select on sequence public.contact_messages_id_seq to anon, authenticated;

drop policy if exists "Visitors can submit contact messages" on public.contact_messages;
create policy "Visitors can submit contact messages"
  on public.contact_messages for insert to anon, authenticated
  with check (
    char_length(name) between 1 and 120
    and char_length(email) between 3 and 254
    and char_length(phone) between 1 and 40
    and char_length(message) between 1 and 5000
  );

drop policy if exists "Authenticated inbox users can read contact messages" on public.contact_messages;
create policy "Authenticated inbox users can read contact messages"
  on public.contact_messages for select to authenticated
  using (true);

drop policy if exists "Authenticated inbox users can delete contact messages" on public.contact_messages;
create policy "Authenticated inbox users can delete contact messages"
  on public.contact_messages for delete to authenticated
  using (true);
